### ISSUE TITLE
4K Poster script gets stuck at first film

### ISSUE THREAD

**Issue by AD1995** [jkirkcaldy/plex-utills#111]
When I run the 4K Posters script, it gets stuck at the first movie and the debug log shows "[filn name] is not in database"

Logs are here

> [2022-06-03 13:21:51,421] - [plex-utills] - [DEBUG] - testing
[2022-06-03 13:21:51,848] - [plex-utills] - [DEBUG] - ['4K-Movies']
[2022-06-03 13:21:52,413] - [plex-utills] - [INFO] - The 355
[2022-06-03 13:21:52,414] - [plex-utills] - [DEBUG] - The 355 Getting poster
[2022-06-03 13:21:52,426] - [plex-utills] - [DEBUG] - The 355 not in database
libpng error: IDAT: CRC error
Exception in thread 4K Poster Script:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/scripts.py", line 1961, in posters4k_thread
    posters4k('')
  File "/app/app/scripts.py", line 360, in posters4k
    run_script()
  File "/app/app/scripts.py", line 345, in run_script
    process(tmp_poster)
  File "/app/app/scripts.py", line 317, in process
    banners = module.check_banners(tmp_poster, size)
  File "/app/app/module.py", line 86, in check_banners
    background = cv2.cvtColor(background, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Plex-utils can see the directories with the films in and running the restore posters script works fine.

**Comment by AD1995** [comment]
Latest update fixed whatever was causing this issue
