### ISSUE TITLE
FileNotFoundError Line 494

### ISSUE THREAD

**Issue by ados8** [jkirkcaldy/plex-utills#112]
Unfortunealy never had much success getting this docker on UNRAID to work well.
In the past the issues were always inability to get poster backups working and corrupt posters which resulted in its removal.
Having seen the big December update last year decided to install again.

Issue: regardless of post backups enabled or disabled the error is the same.

`2022-06-14 12:08:07,850 - SYS - 4K/HDR Posters schedule created for 23:00`
`2022-06-14 12:08:09,874 - SYS - Updater: Your plexpath has been changed to /movies`
`2022-06-14 12:08:09,875 - SYS - Updater: Your plexpath has been changed to /movies`
`2022-06-14 12:08:10,353 - SYS - Updater: Your plexpath has been changed to /movies`
`2022-06-14 12:08:10,353 - SYS - Updater: Your plexpath has been changed to /movies`
`2022-06-14 12:08:31,628 - plex-utills - 4k Posters: 4k HDR poster script starting now.`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
`File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner`
`self.run()`
`File "/usr/local/lib/python3.9/threading.py", line 910, in run`
`self._target(*self._args, **self._kwargs)`
`File "/app/app/scripts.py", line 1184, in posters4k`
`m = MediaInfo.parse(file, output='JSON')`
`File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse`
`raise FileNotFoundError(filename)`
`FileNotFoundError: /films/1BR (2019)/1BR (2019).mkv`
`2022-06-14 12:13:46,518 - plex-utills - 4k Posters: 4k HDR poster script starting now.`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
`File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner`
`self.run()`
`File "/usr/local/lib/python3.9/threading.py", line 910, in run`
`self._target(*self._args, **self._kwargs)`
`File "/app/app/scripts.py", line 1184, in posters4k`
`m = MediaInfo.parse(file, output='JSON')`
`File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse`
`raise FileNotFoundError(filename)`
`FileNotFoundError: /films/1BR (2019)/1BR (2019).mkv`

When checking the help section it indicates no issues.
![image](https://user-images.githubusercontent.com/49982433/173479760-ecfe1d2d-883a-465b-b3c3-98c88093c7b0.png)
I have also checked permissions and the docker is the same as that of Plex it also can see the file within the container.
![image](https://user-images.githubusercontent.com/49982433/173480187-032ae8c9-5f66-4370-a0c9-ae1b5eb76296.png)
The permissions have also been lowered for testing
![image](https://user-images.githubusercontent.com/49982433/173480352-4b611296-a9d7-4d2b-b2ad-fbaf4ff776e1.png)

I'm thinking this is a bug in the script itself.

**Comment by ados8** [comment]
> I'm having the same issue. For some reason it seems to only happen to me when I scan my movies. it works okay when I scan TV Series. I'm also having issues where it will randomly corrupt a poster and I have to go into Plex and choose the non-corrupted poster.

I gave up on this one, I was thinking of moving to Emby for a year and finally pulled the trigger. All my users are far happier and so am I, Plex has lost their way adding fluff features and the underlying video player is so unstable and trash now. Emby is cheaper and better than Plex in every performance point.

**Comment by jkirkcaldy** [comment]
Does this still happen on the :latest container?
