### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by mtlballer** [jkirkcaldy/plex-utills#126]
"It looks like you've upgraded and need to migrate.

Click the button below to migrate your install."

_Upon clicking the Migrate button I get the following Script log file output before it just stops:_

[2023-03-17 06:27:36,785] - [plex-utills] - [ERROR] - [Errno 2] No such file or directory: '/tmp/com.plexapp.agents.imdb://tt0322259?lang=en.png'
[2023-03-17 06:27:35,304] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious Getting poster
[2023-03-17 06:27:35,211] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious
[2023-03-17 06:27:33,875] - [plex-utills] - [DEBUG] - ['4K Movies']

_Along with this log via docker:_

  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x154200ba9190>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154200ba9190>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/scripts.py", line 1663, in fill_database
    from app import module
  File "/app/app/module.py", line 20, in <module>
    plex = PlexServer(config[0].plexurl, config[0].token)
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='plex', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x154200ba9190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2023-03-17 06:25:44,563] - [Application] - [DEBUG] - Running Updater
[2023-03-17 06:26:32,547] - [Application] - [DEBUG] - Running Updater
[2023-03-17 06:26:32,602] - [Application] - [INFO] - posters4k (trigger: cron[hour='4', minute='0'], next run at: 2023-03-18 04:00:00 EDT)
[2023-03-17 06:27:33,875] - [plex-utills] - [DEBUG] - ['4K Movies']
[2023-03-17 06:27:35,211] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious
[2023-03-17 06:27:35,304] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious Getting poster
[2023-03-17 06:27:36,785] - [plex-utills] - [ERROR] - [Errno 2] No such file or directory: '/tmp/com.plexapp.agents.imdb://tt0322259?lang=en.png'
[ WARN:0@386.485] global loadsave.cpp:244 findDecoder imread_(''): can't open/read file: check file path/integrity
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/scripts.py", line 2003, in fill_database
    run_script()
  File "/app/app/scripts.py", line 1975, in run_script
    main()
  File "/app/app/scripts.py", line 1946, in main
    banners = module.check_banners(tmp_poster, poster_size)
  File "/app/app/module.py", line 104, in check_banners
    background = cv2.cvtColor(background, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I've tried a full re-install, any help would be appreciated.

**Comment by Nelinski** [comment]
I've got the same issue too.

**Comment by Schmackei** [comment]
> [2023-03-17 06:27:36,785] - [plex-utills] - [ERROR] - [Errno 2] No such file or directory: '/tmp/com.plexapp.agents.imdb://tt0322259?lang=en.png' [2023-03-17 06:27:35,304] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious Getting poster [2023-03-17 06:27:35,211] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious [2023-03-17 06:27:33,875] - [plex-utills] - [DEBUG] - ['4K Movies']

This error is caused because in Plex, the Movie is not correctly matched. Go into your 4k Movies library and locate 2 Fast 2 Furious and select the 3 dots > match/fix match. then restart the migrate again, this will happen for every movie that you have that is not matched correctly.

**Comment by mtlballer** [comment]
> > [2023-03-17 06:27:36,785] - [plex-utills] - [ERROR] - [Errno 2] No such file or directory: '/tmp/com.plexapp.agents.imdb://tt0322259?lang=en.png' [2023-03-17 06:27:35,304] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious Getting poster [2023-03-17 06:27:35,211] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious [2023-03-17 06:27:33,875] - [plex-utills] - [DEBUG] - ['4K Movies']
> 
> This error is caused because in Plex, the Movie is not correctly matched. Go into your 4k Movies library and locate 2 Fast 2 Furious and select the 3 dots > match/fix match. then restart the migrate again, this will happen for every movie that you have that is not matched correctly.

Thanks for the help! Seems like every movie in my library has this issue, most likely due to the plex agent migration? I'll check back in once I've managed to fix the entire library!

**Comment by Schmackei** [comment]
> > > [2023-03-17 06:27:36,785] - [plex-utills] - [ERROR] - [Errno 2] No such file or directory: '/tmp/com.plexapp.agents.imdb://tt0322259?lang=en.png' [2023-03-17 06:27:35,304] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious Getting poster [2023-03-17 06:27:35,211] - [plex-utills] - [DEBUG] - 2 Fast 2 Furious [2023-03-17 06:27:33,875] - [plex-utills] - [DEBUG] - ['4K Movies']
> > 
> > 
> > This error is caused because in Plex, the Movie is not correctly matched. Go into your 4k Movies library and locate 2 Fast 2 Furious and select the 3 dots > match/fix match. then restart the migrate again, this will happen for every movie that you have that is not matched correctly.
> 
> Thanks for the help! Seems like every movie in my library has this issue, most likely due to the plex agent migration? I'll check back in once I've managed to fix the entire library!

Ouch, yeah, i had about 40 movies with the issue and it took a while to sort as i had to begin the migration after each match.

**Comment by mtlballer** [comment]
Took a few hours but it is done and did indeed work! @Schmackei many thanks! Ended up being at least 75% of the library, I just gave up and did them all lol.

@Nelinski Try the fix suggested if you have the same error!
