### ISSUE TITLE
Spoilers Failing with no attribute

### ISSUE THREAD

**Issue by Scridgeon** [jkirkcaldy/plex-utills#131]
I'm trying to use the Spoilers feature but it's not working. The Plex-Utils front end is giving me a 500 error on the page and I see the following error in the application logs.

I'm using the docker application on Unraid and passed my Library. Plex-Utils can see both my TV and Movies in the respective sections in the UI.
I also have "Enable the blur unwatched TV episodes script" = True

![image](https://github.com/jkirkcaldy/plex-utills/assets/18316138/c1349040-a183-44f5-9af7-b8e7e9a91337)

[2023-05-23 13:01:38,594] ERROR in app: Exception on /spoilers [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/routes.py", line 261, in run_tvspoilers
    Thread(target=scripts.spoilers_scheduled, args=[app]).start()
AttributeError: module 'app.scripts' has no attribute 'spoilers_scheduled'

**Comment by stuartg78** [comment]
Did you get this to work?  Having the same issue.

**Comment by sneedster** [comment]
Same error here too, also running on unraid.
