### ISSUE TITLE
ModuleNotFoundError: No module named 'plexapi'

### ISSUE THREAD

**Issue by douginoz** [jkirkcaldy/plex-utills#2]
For various unchangeable reasons, I still need to run pip and python2.7 as well as python3.  I have both installed.  However, it appears to my layman's eyes that the installation line "sudo pip install -r requirements.txt" actually installs the plexapi module somewhere in python2.7 land.  When I subsequently try to run  'python3 4klibrary.py ', it returns
Traceback (most recent call last):
  File "4klibrary.py", line 4, in <module>
    from plexapi.server import PlexServer
ModuleNotFoundError: No module named 'plexapi'

I git cloned as root and ran the installation steps as root, and am running the 4klibrary.py as root, which I assume is correct.  

Is there a way to install the plexapi so that python3 will see it?

**Comment by douginoz** [comment]
Here's the installation on my ubuntu 18.04 system that led me to believe this is a python2.7 vs 3 issue (but I'm not a coder so....)
```
sudo pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting plexapi==3.2.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/87/e2/93f4102634abda495e6b47e2e30c19a91ad61938f83b46edc8c20891b41d/PlexAPI-3.2.0.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 2.4MB/s 
Collecting configparser==4.0.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from plexapi==3.2.0->-r requirements.txt (line 1)) (2.21.0)
Collecting tqdm (from plexapi==3.2.0->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/47/55/fd9170ba08a1a64a18a7f8a18f088037316f2a41be04d2fe6ece5a653e8f/tqdm-4.43.0-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 15.7MB/s 
Requirement already satisfied: websocket-client in /usr/local/lib/python2.7/dist-packages (from plexapi==3.2.0->-r requirements.txt (line 1)) (0.57.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->plexapi==3.2.0->-r requirements.txt (line 1)) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->plexapi==3.2.0->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests->plexapi==3.2.0->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/dist-packages (from requests->plexapi==3.2.0->-r requirements.txt (line 1)) (2.6)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from websocket-client->plexapi==3.2.0->-r requirements.txt (line 1)) (1.11.0)
Building wheels for collected packages: plexapi
  Building wheel for plexapi (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/d4/0b/d8/aedfd16b8439714093c875ffe88949655b6130ba3d26d8898d
Successfully built plexapi
Installing collected packages: tqdm, plexapi, configparser
Successfully installed configparser-4.0.2 plexapi-3.2.0 tqdm-4.43.0
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

root@sophie:/opt/plex-utills#nano config.ini
[PLEXSERVER]
PLEX_URL = https://myserver:32400
TOKEN = 2AB4BV5TD56ABCDEF etc
FILMSLIBRARY = Movies

root@sophie:/opt/plex-utills# python3 4klibrary.py 
Traceback (most recent call last):
  File "4klibrary.py", line 4, in <module>
    from plexapi.server import PlexServer
ModuleNotFoundError: No module named 'plexapi'
root@sophie:/opt/plex-utills# 

```

**Comment by douginoz** [comment]
Ah, I'm learning as I go.  It appears that you can run multiple versions of pip via the recommended approach:
sudo python -m pip install -r requirements.txt

In my case, I used
sudo python3 -m pip install -r requirements.txt

which installed the requirements in python3 space.

Unfortunately, when I then run 4klibrary.py, it fails:
```

root@sophie:/opt/plex-utills# python3 4klibrary.py 
Traceback (most recent call last):
  File "4klibrary.py", line 25, in <module>
    movies_section = plex.library.section('films')
  File "/usr/local/lib/python3.6/dist-packages/plexapi/library.py", line 55, in section
    raise NotFound('Invalid library section: %s' % title)
plexapi.exceptions.NotFound: Invalid library section: films
root@sophie:/opt/plex-utills# cat config.ini 
[PLEXSERVER]
PLEX_URL = http://sophie:32400
TOKEN = 2V71xz6jBnX-z1usfFNw
FILMSLIBRARY = Movies
root@sophie:/opt/plex-utills#

I suspect the library "films" is hard coded and isn't using whatever is in the config.ini?
```

**Comment by douginoz** [comment]
I worked around it with this code substitution:

#    movies_section = plex.library.section('films')
    movies_section = plex.library.section('Movies')

I "hard-coded" the name of my library, and it works OK.
