### ISSUE TITLE
error connection 

### ISSUE THREAD

**Issue by ptichalouf** [jkirkcaldy/plex-utills#35]
hello I try to use this with Unraid and docker but I have this error. I'm sur the URL is good and the token too 

Traceback (most recent call last):
File "/app/./run_all.py", line 37, in <module>
plex = PlexServer(baseurl, token)
File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 116, in __init__
data = self.query(self.key, timeout=self._timeout)
File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 659, in query
response = method(url, headers=headers, timeout=timeout, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.41', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x150f49a77940>: Failed to establish a new connection: [Errno 113] No route to host'))

**Comment by ApfelBirneKreis** [comment]
I have the same issue here.

Log Snippet:

```
/config/config.ini exists
Config check passed
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
conn = connection.create_connection(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
raise err
File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1303, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1252, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1012, in _send_output
self.send(msg)
File "/usr/local/lib/python3.9/http/client.py", line 952, in send
self.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
conn = self._new_conn()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x15392914e940>: Failed to establish a new connection: [Errno 113] No route to host


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.178.2', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15392914e940>: Failed to establish a new connection: [Errno 113] No route to host'))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/./run_all.py", line 37, in <module>
plex = PlexServer(baseurl, token)
File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 116, in __init__
data = self.query(self.key, timeout=self._timeout)
File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 659, in query
response = method(url, headers=headers, timeout=timeout, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.178.2', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x15392914e940>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by jkirkcaldy** [comment]
What is your docker network type? 

Can you try changing it to bridge?

**Comment by ApfelBirneKreis** [comment]
Network type is already Bridge. The Container won´t even start on other types.

**Comment by ApfelBirneKreis** [comment]
i managed to get it working by switching it to host mode and giving it a private route to the plex container..

but now there is another error while replacing the banners.

`20:34:48 : 4k HDR poster script starting now.
1917 4k HDR
 Creating a backup file 
Filme [4K UHD] Error, the 4k HDR poster for this film could not be created.`

Nothing shows up in the logs. I tryed to giving it privilleged access but that did not solve the problem. 
Do the movie files or names need to be the original names

**Comment by jkirkcaldy** [comment]
That usually happens when the script can't write to the movie directory. 

What's the mount point for your Plex media? 

And what plex docker container are you using?

**Comment by ApfelBirneKreis** [comment]
Mount Paths in PlexUtils:

![image](https://user-images.githubusercontent.com/84158946/130455449-d8645967-7860-46e8-9236-4ca10f3cbb67.png)

Mount Paths in Plex:

![image](https://user-images.githubusercontent.com/84158946/130455605-bfb7b2ef-4e51-4f40-9f44-9eadcef2bed1.png)

I am using the official Plex container.
https://hub.docker.com/r/plexinc/pms-docker/


The PlexUtils is running in privilleged mode and the plex data folder has all permissions open via chmod 777 -R /pathtoplexdata

**Comment by jkirkcaldy** [comment]
did you change the `MOUNTEDPATH` in the config?

**Comment by ApfelBirneKreis** [comment]
Config Snipped:

```
# This should match the library title seen in Plex
FILMSLIBRARY = Filme [4K UHD]
3D_Library = 3D-Films
#Use the setup helper if you don't know what to use here.
PLEXPATH = /films

# If using Docker, leave this as /films. No trailing slash.
MOUNTEDPATH = /films
```

**Comment by jkirkcaldy** [comment]
Ok, your `PLEXPATH` should be `/data`

**Comment by ApfelBirneKreis** [comment]
Thank you so much! That solved it!
