### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by milindpatel63** [jkirkcaldy/plex-utills#50]
First, the schedules are not working...no matter what time I set, they don't go off...
Second, none of the scripts work...i get the following error..

2021-10-29 06:42:36,951 - Plex-Utills - INFO - 4k Posters: 4k HDR poster script starting now.
2021-10-29 06:42:36,951 - Plex-Utills - INFO - 4k Posters: 4K/HDR Poster Script has finished.
2021-10-29 06:42:36,952 - app - ERROR - Exception on /recreate_hdr_script [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'run_recreate_hdr_script' did not return a valid response. The function either returned None or ended without a return statement.

and after that, all my hdr symbols from all my posters are gone

**Comment by jkirkcaldy** [comment]
Are you still having issues with this. 
The error you are getting was an issue with the flask app and not an error of the poster scripts which has been addressed in the recent update. 

The recreate HDR scripts should remove all the HDR banners and then go through and recreate them.

**Comment by jkirkcaldy** [comment]
Closed due to inactivity
