### ISSUE TITLE
app - ERROR - Exception on /posters4k [GET]

### ISSUE THREAD

**Issue by wgstarks** [jkirkcaldy/plex-utills#51]
2021-10-31 12:46:59,231 - app - ERROR - Exception on /posters4k [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/./app/routes.py", line 29, in run_posters4k
    return posters4k()
  File "/app/./app/scripts.py", line 349, in posters4k
    films = plex.library.section(config[0][3])
UnboundLocalError: local variable 'plex' referenced before assignment

I get this error any time I try to run the 4k script.
Running the most recent version of the docker on unraid.

**Comment by jkirkcaldy** [comment]
Update coming that should fix this.

**Comment by wgstarks** [comment]
Thx

**Comment by wgstarks** [comment]
Fixed with 0.21.9 beta.
