### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by seannymurrs** [jkirkcaldy/plex-utills#6]
I get the following error when running the script.  

`Traceback (most recent call last):
  File "4klibrary.py", line 46, in <module>
    entry.removeLabel('Transcodable')
  File "/home/seannymurrs/.local/lib/python3.7/site-packages/plexapi/base.py", line 381, in removeLabel
    self._edit_tags('label', labels, remove=True)
  File "/home/seannymurrs/.local/lib/python3.7/site-packages/plexapi/base.py", line 361, in _edit_tags    self.refresh()
  File "/home/seannymurrs/.local/lib/python3.7/site-packages/plexapi/base.py", line 407, in refresh
    self._server.query(key, method=self._server._session.put)
  File "/home/seannymurrs/.local/lib/python3.7/site-packages/plexapi/server.py", line 381, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (404) not_found; https://xxxxxxx/library/metadata/112130/refresh <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html> `

**Comment by jkirkcaldy** [comment]
Are you still having issues when running the script?
