### ISSUE TITLE
Still not able to get this working.

### ISSUE THREAD

**Issue by jlyfshhh** [jkirkcaldy/plex-utills#62]
I have a previous issue open that I was getting errors with it unable to change any posters, so I deleted everything and wanted for an update. I started over today and now I get this. Does anyone actually have this working? I've never been able to get this to do anything.

2021-11-20 19:31:06,320 - apscheduler.scheduler - INFO - Scheduler started
2021-11-20 19:32:10,179 - apscheduler.scheduler - INFO - Added job "posters4k" to job store "default"
2021-11-20 19:32:10,179 - root - INFO - 4K/HDR Posters schedule created for 00:00
2021-11-20 19:32:52,859 - app - ERROR - Exception on /posters4k [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.4.6', port=32400): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/./app/routes.py", line 29, in run_posters4k
    return posters4k()
  File "/app/./app/scripts.py", line 57, in posters4k
    plex = PlexServer(config[0][1], config[0][2])
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 116, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 659, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.4.6', port=32400): Read timed out. (read timeout=30)

**Comment by jkirkcaldy** [comment]
Are you on the latest version?   
  

  
It’s having trouble connecting to your Plex server. That’s what the timeouts are. Can the Plex-utills    docker see your Plex server?   
  

  
You can go to  <plex-utills-ip>:<port>/help and see if everything shows up.   
  
  
  
    
  

  
  
>

**Comment by jlyfshhh** [comment]
Ok so I think it might have been a docker networking issue so I added it to my docker-compose with my Plex and now I have this

2021-11-21 20:45:09,764 - plex-utills - 4k Posters: 4k HDR poster script starting now.
2021-11-21 20:45:10,360 - plex-utills - 4k Posters: Creating 4K posters only

Does that mean it's working? It's been sitting there for a while.

**Comment by jkirkcaldy** [comment]
It should start to list off all the films and that it's creating posters for them.

**Comment by jkirkcaldy** [comment]
> Ok so I think it might have been a docker networking issue so I added it to my docker-compose with my Plex and now I have this
> 
> 2021-11-21 20:45:09,764 - plex-utills - 4k Posters: 4k HDR poster script starting now. 2021-11-21 20:45:10,360 - plex-utills - 4k Posters: Creating 4K posters only
> 
> Does that mean it's working? It's been sitting there for a while.

Does the docker log show any more information?

**Comment by jlyfshhh** [comment]
Alright so I deleted everything and started from scratch. Worked perfectly this time for the movie posters! I was getting this error for all of the tv shows though:

2021-11-22 19:52:06,361 - plex-utills - Coming Home 4K Poster
2021-11-22 19:52:06,396 - plex-utills - 4k Posters: Creating a backup file
2021-11-22 19:52:06,397 - plex-utills - [Errno 2] No such file or directory: '/tv/Yellowstone (2018) [imdb-tt4236770]/Season 01/poster_bak.png'
2021-11-22 19:52:06,397 - plex-utills - 4k Posters: TV Shows The 4k poster for this episode could not be created
2021-11-22 19:52:06,397 - plex-utills - This is likely because poster backups are enabled and the script can't find or doesn't have access to your backup location

**Comment by jkirkcaldy** [comment]
Can you go to the <ip:port>/help and screen shot that page.
