### ISSUE TITLE
File not found error!

### ISSUE THREAD

**Issue by chacuavip10** [jkirkcaldy/plex-utills#82]
Got script hangging:
2021-12-28 22:39:50,449 - plex-utills - 4k Posters: 4k HDR poster script starting now.
2021-12-28 22:39:50,914 - plex-utills - 2012 - 4k Posters: Backup file exists, skipping
2021-12-28 22:39:50,915 - plex-utills - 2012 4K HDR
2021-12-28 22:39:51,033 - plex-utills - HDR Banner: 2012 hdr banner exists moving on
2021-12-28 22:39:51,151 - plex-utills - 4k Posters: Mini 4k banner exists, moving on
2021-12-28 22:39:51,670 - plex-utills - Army of Thieves - 4k Posters: Backup file exists, skipping
2021-12-28 22:39:51,671 - plex-utills - Army of Thieves 4K HDR
2021-12-28 22:39:51,815 - plex-utills - HDR Banner: Army of Thieves hdr banner exists
2021-12-28 22:39:51,817 - plex-utills - HDR Banner: Army of Thieves adding dolby-vision hdr banner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/scripts.py", line 607, in posters4k
    poster_4k_hdr()
  File "/app/app/scripts.py", line 504, in poster_4k_hdr
    add_new_hdr()
  File "/app/app/scripts.py", line 285, in add_new_hdr
    dolby_vision()
  File "/app/app/scripts.py", line 240, in dolby_vision
    background = Image.open(tmp_poster)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Army_of_Thieves_poster.png'

Console to the container, got no such poster in tmp folder
root@9e723f7390ab:/app/app# ls -lh /tmp/
total 2.2M
-rw-r--r-- 1 root root 1.9M Dec 28 22:42 poster.png
-rw------- 1 root root 254K Dec  3 08:16 tmpvxml2gcxcacert.pem

**Comment by chacuavip10** [comment]
Update.
Fix it by manually changing the poster in plex then rerun the script.
