### ISSUE TITLE
[Errno 2] No such file or directory: - Then it hangs

### ISSUE THREAD

**Issue by russellmoran99** [jkirkcaldy/plex-utills#88]
@jkirkcaldy - I am still using the dev version.  My family binge watched The Hobbit and Lord of the Rings this last few weeks and realized we had the Extended Versions.  I was able to get the Theatrical versions recently.  I have it setup as following:

/4K Movies/The Hobbit An Unexpected Journey (2012)/The Hobbit An Unexpected Journey (2012) Remux-2160p 7.1 BdC - Theatrical Cut.mkv

and

/4K Movies/The Hobbit An Unexpected Journey (2012) - Extended/The Hobbit An Unexpected Journey (2012) Remux-2160p 7.1 FraMeSToR - Extended.mkv

Notice the Extended and Theatrical are in separate folders.  I now get this message:

2022-01-03 13:56:05,586 - plex-utills - The Hobbit: An Unexpected Journey - Posters: Creating a backup file
2022-01-03 13:56:05,596 - plex-utills - The Hobbit: An Unexpected Journey Atmos Poster
2022-01-03 13:56:05,700 - plex-utills - 4k Posters: Atmos banner exists, moving on
2022-01-03 13:56:05,700 - plex-utills - The Hobbit: An Unexpected Journey 4K HDR
2022-01-03 13:56:05,907 - plex-utills - HDR Banner: The Hobbit: An Unexpected Journey dolby-vision banner exists
2022-01-03 13:56:05,916 - plex-utills - HDR Banner: The Hobbit: An Unexpected Journey adding hdr banner now
2022-01-03 13:56:05,916 - plex-utills - [Errno 2] No such file or directory: '/tmp/The_Hobbit__An_Unexpected_Journey_poster.png'

Once this happens, it just sets there. Any suggestions?  Thanks

**Comment by russellmoran99** [comment]
@jkirkcaldy Here is some more from the docker log.

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/app/app/scripts.py", line 625, in posters4k
poster_4k_hdr()
File "/app/app/scripts.py", line 543, in poster_4k_hdr
check_for_banner()
File "/app/app/scripts.py", line 152, in check_for_banner
background = Image.open(tmp_poster)
File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2975, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/The_Hobbit__An_Unexpected_Journey_poster.png'

**Comment by jkirkcaldy** [comment]
Just pushed an update, hopefully it should sort the issue for you.

**Comment by russellmoran99** [comment]
I am using the DEV update.  I ran a force update and ran the script again.  

Similar or same error message:

2022-01-04 12:15:03,963 - plex-utills - The Hobbit: An Unexpected Journey - 4k Posters: Backup file exists, skipping
2022-01-04 12:15:03,963 - plex-utills - The Hobbit: An Unexpected Journey Atmos Poster
2022-01-04 12:15:04,058 - plex-utills - 4k Posters: Atmos banner exists, moving on
2022-01-04 12:15:04,059 - plex-utills - The Hobbit: An Unexpected Journey 4K HDR
2022-01-04 12:15:04,255 - plex-utills - HDR Banner: The Hobbit: An Unexpected Journey dolby-vision banner exists
2022-01-04 12:15:04,262 - plex-utills - HDR Banner: The Hobbit: An Unexpected Journey adding hdr banner now
2022-01-04 12:15:04,263 - plex-utills - [Errno 2] No such file or directory: '/tmp/The_Hobbit__An_Unexpected_Journey_poster.png'
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/app/app/scripts.py", line 639, in posters4k
poster_4k_hdr()
File "/app/app/scripts.py", line 546, in poster_4k_hdr
check_for_banner()
File "/app/app/scripts.py", line 152, in check_for_banner
background = Image.open(tmp_poster)
File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2953, in open
fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/The_Hobbit__An_Unexpected_Journey_poster.png'

**Comment by jkirkcaldy** [comment]
Ok. I'll have another look and see what's going on.

**Comment by russellmoran99** [comment]
@jkirkcaldy Thanks for the help.  Let me know if you need me to do anything on my end.  You're awesome as always!

**Comment by jkirkcaldy** [comment]
pushed out a new :dev container that should help. Trying to catch the error then move on to the next film.

**Comment by russellmoran99** [comment]
@jkirkcaldy  The new push worked! Thanks again.  Out of curiosity, why did this one file fail?

**Comment by jkirkcaldy** [comment]
I'm not sure. I can only assume it was something to do with having multiple copies of the film. But I'm glad it's been sorted for you.

**Comment by russellmoran99** [comment]
That's weird because I have multiple versions of all 3 Hobbits and 3 Lord of the Rings and it didn't error on any of those.  The file format is identical among all.  Very strange, but thanks for the fix.
