### ISSUE TITLE
ERROR when running python3.7 4k_hdr_poster.py

### ISSUE THREAD

**Issue by hthighwaymonk** [jkirkcaldy/plex-utills#9]
**config.ini**
```
[PLEXSERVER]
PLEX_URL = http://127.0.0.1:32400
TOKEN = *******************
FILMSLIBRARY = Movies - 4K
#Use the setup helper if you don't know what to use here.
PLEXPATH = /mnt/unionfs/movies/4k
# no trailing slash.
MOUNTEDPATH = /mnt/unionfs/movies/4k
```

**message returned**
```
$ python3.7 4k_hdr_poster.py
Traceback (most recent call last):
  File "4k_hdr_poster.py", line 20, in <module>
    mpath = (server["MOUTEDPATH"])
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'MOUTEDPATH'
```

**Comment by hthighwaymonk** [comment]
issue fixed with code update
