### ISSUE TITLE
4K/HDR script not doing anything

### ISSUE THREAD

**Issue by AdamGoodApp** [jkirkcaldy/plex-utills#94]
I tried to run the 4K/HDR script manually but nothing happens. The log shows 4k HDR poster script starting now and then nothing else.

2021-12-15 04:13:02,696 - plex-utills - 4k Posters: 4k HDR poster script starting now.
2021-12-15 04:20:19,937 - plex-utills - Autocollections has started
2021-12-15 04:20:34,565 - plex-utills - Popular Collection has finished
2021-12-15 04:20:36,903 - plex-utills - Top Rated Collection has finished
2021-12-15 04:28:59,100 - plex-utills - 4k Posters: 4k HDR poster script starting now.
2021-12-15 04:32:41,981 - plex-utills - Hide-4K: Hide 4k films script starting now
2021-12-15 04:32:43,588 - plex-utills - Hide-4K: Up has only 4k avaialble, setting untranscodable
2021-12-15 04:32:43,708 - plex-utills - Hide-4K: The Matrix has only 4k avaialble, setting untranscodable
2021-12-15 04:32:43,865 - plex-utills - Hide-4K: The Matrix Reloaded has only 4k avaialble, setting untranscodable
2021-12-15 04:32:44,009 - plex-utills - Hide-4K: The Matrix Revolutions has only 4k avaialble, setting untranscodable
2021-12-15 04:32:44,123 - plex-utills - Hide-4K: Sympathy for Lady Vengeance has only 4k avaialble, setting untranscodable
2021-12-15 04:32:44,459 - plex-utills - Hide-4K: Sympathy for Mr. Vengeance has only 4k avaialble, setting untranscodable
2021-12-15 04:32:44,600 - plex-utills - Hide-4K: The Lord of the Rings: The Fellowship of the Ring has only 4k avaialble, setting untranscodable
2021-12-15 04:32:44,740 - plex-utills - Hide-4K: The Lord of the Rings: The Two Towers has only 4k avaialble, setting untranscodable
2021-12-15 04:32:44,823 - plex-utills - Hide-4K: Parasite has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,125 - plex-utills - Hide-4K: The Lord of the Rings: The Return of the King has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,275 - plex-utills - Hide-4K: Star Wars: Episode IV - A New Hope has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,417 - plex-utills - Hide-4K: The Dark Knight has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,490 - plex-utills - Hide-4K: Finding Nemo has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,591 - plex-utills - Hide-4K: Monsters, Inc. has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,755 - plex-utills - Hide-4K: Batman Begins has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,886 - plex-utills - Hide-4K: Men in Black II has only 4k avaialble, setting untranscodable
2021-12-15 04:32:45,994 - plex-utills - Hide-4K: Terminator 2: Judgment Day has only 4k avaialble, setting untranscodable
2021-12-15 04:32:46,126 - plex-utills - Hide-4K: Star Wars: Episode V - The Empire Strikes Back has only 4k avaialble, setting untranscodable
2021-12-15 04:32:46,467 - plex-utills - Hide-4K: The Incredibles has only 4k avaialble, setting untranscodable
2021-12-15 04:32:46,630 - plex-utills - Hide-4K: WALL·E has only 4k avaialble, setting untranscodable
2021-12-15 04:32:46,788 - plex-utills - Hide-4K: The Hobbit: An Unexpected Journey has only 4k avaialble, setting untranscodable
2021-12-15 04:32:46,916 - plex-utills - Hide-4K: X-Men: The Last Stand has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,084 - plex-utills - Hide-4K: The Hobbit: The Battle of the Five Armies has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,196 - plex-utills - Hide-4K: Us has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,335 - plex-utills - Hide-4K: The Hobbit: The Desolation of Smaug has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,523 - plex-utills - Hide-4K: The Irishman has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,631 - plex-utills - Hide-4K: Once Upon a Time... In Hollywood has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,738 - plex-utills - Hide-4K: Spider-Man has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,852 - plex-utills - Hide-4K: Iron Man has only 4k avaialble, setting untranscodable
2021-12-15 04:32:47,970 - plex-utills - Hide-4K: X-Men has only 4k avaialble, setting untranscodable
2021-12-15 04:32:48,132 - plex-utills - Hide-4K: X-Men: First Class has only 4k avaialble, setting untranscodable
2021-12-15 04:32:48,253 - plex-utills - Hide-4K: The Avengers has only 4k avaialble, setting untranscodable
2021-12-15 04:32:48,593 - plex-utills - Hide-4K: Iron Man 3 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:48,726 - plex-utills - Hide-4K: Get Out has only 4k avaialble, setting untranscodable
2021-12-15 04:32:48,861 - plex-utills - Hide-4K: Captain Marvel has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,010 - plex-utills - Hide-4K: Spider-Man: Far from Home has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,154 - plex-utills - Hide-4K: Thor: The Dark World has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,302 - plex-utills - Hide-4K: Avengers: Age of Ultron has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,419 - plex-utills - Hide-4K: X-Men: Days of Future Past has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,525 - plex-utills - Hide-4K: Dunkirk has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,669 - plex-utills - Hide-4K: Men in Black has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,801 - plex-utills - Hide-4K: Men in Black 3 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:49,974 - plex-utills - Hide-4K: Captain America: The Winter Soldier has only 4k avaialble, setting untranscodable
2021-12-15 04:32:50,099 - plex-utills - Hide-4K: Spider-Man: Into the Spider-Verse has only 4k avaialble, setting untranscodable
2021-12-15 04:32:50,255 - plex-utills - Hide-4K: Guardians of the Galaxy has only 4k avaialble, setting untranscodable
2021-12-15 04:32:50,585 - plex-utills - Hide-4K: Guardians of the Galaxy Vol. 2 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:50,759 - plex-utills - Hide-4K: Avengers: Endgame has only 4k avaialble, setting untranscodable
2021-12-15 04:32:50,865 - plex-utills - Hide-4K: Avengers: Infinity War has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,032 - plex-utills - Hide-4K: Spider-Man: Homecoming has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,142 - plex-utills - Hide-4K: Spider-Man 2 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,269 - plex-utills - Hide-4K: Battle Royale has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,412 - plex-utills - Hide-4K: Iron Man 2 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,558 - plex-utills - Hide-4K: Captain America: Civil War has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,713 - plex-utills - Hide-4K: Captain America: The First Avenger has only 4k avaialble, setting untranscodable
2021-12-15 04:32:51,871 - plex-utills - Hide-4K: Ant-Man has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,024 - plex-utills - Hide-4K: Ant-Man and the Wasp has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,139 - plex-utills - Hide-4K: Thor has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,281 - plex-utills - Hide-4K: Thor: Ragnarok has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,447 - plex-utills - Hide-4K: X-Men: Apocalypse has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,571 - plex-utills - Hide-4K: Deadpool has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,715 - plex-utills - Hide-4K: Deadpool 2 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:52,857 - plex-utills - Hide-4K: Black Panther has only 4k avaialble, setting untranscodable
2021-12-15 04:32:53,220 - plex-utills - Hide-4K: Black Widow has only 4k avaialble, setting untranscodable
2021-12-15 04:32:53,404 - plex-utills - Hide-4K: Star Wars: Episode IX - The Rise of Skywalker has only 4k avaialble, setting untranscodable
2021-12-15 04:32:53,557 - plex-utills - Hide-4K: Star Wars: Episode VIII - The Last Jedi has only 4k avaialble, setting untranscodable
2021-12-15 04:32:53,710 - plex-utills - Hide-4K: Star Wars: Episode VII - The Force Awakens has only 4k avaialble, setting untranscodable
2021-12-15 04:32:53,848 - plex-utills - Hide-4K: Star Wars: Episode I - The Phantom Menace has only 4k avaialble, setting untranscodable
2021-12-15 04:32:53,972 - plex-utills - Hide-4K: Star Wars: Episode III - Revenge of the Sith has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,120 - plex-utills - Hide-4K: Star Wars: Episode VI - Return of the Jedi has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,232 - plex-utills - Hide-4K: Incredibles 2 has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,326 - plex-utills - Hide-4K: Blade Runner has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,428 - plex-utills - Hide-4K: Blade has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,524 - plex-utills - Hide-4K: The Fifth Element has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,638 - plex-utills - Hide-4K: Goodfellas has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,742 - plex-utills - Hide-4K: The Shawshank Redemption has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,856 - plex-utills - Hide-4K: Logan has only 4k avaialble, setting untranscodable
2021-12-15 04:32:54,957 - plex-utills - Hide-4K: Interstellar has only 4k avaialble, setting untranscodable
2021-12-15 04:32:55,059 - plex-utills - Hide-4K: Donnie Darko has only 4k avaialble, setting untranscodable
2021-12-15 04:32:55,499 - plex-utills - Hide-4K: Underworld has only 4k avaialble, setting untranscodable
2021-12-15 04:32:55,600 - plex-utills - Hide-4K: Alien has only 4k avaialble, setting untranscodable
2021-12-15 04:32:55,734 - plex-utills - Hide-4K: Schindler's List has only 4k avaialble, setting untranscodable
2021-12-15 04:32:55,849 - plex-utills - Hide-4K: The Amazing Spider-Man has only 4k avaialble, setting untranscodable
2021-12-15 04:32:55,961 - plex-utills - Hide-4K: Hellboy II: The Golden Army has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,050 - plex-utills - Hide-4K: The Mummy Returns has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,150 - plex-utills - Hide-4K: Underworld: Rise of the Lycans has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,271 - plex-utills - Hide-4K: The Martian has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,366 - plex-utills - Hide-4K: Saving Private Ryan has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,469 - plex-utills - Hide-4K: Inglourious Basterds has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,574 - plex-utills - Hide-4K: Underworld: Evolution has only 4k avaialble, setting untranscodable
2021-12-15 04:32:56,671 - plex-utills - Hide-4K: Full Metal Jacket has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,047 - plex-utills - Hide-4K: Resident Evil has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,163 - plex-utills - Hide-4K: Prometheus has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,266 - plex-utills - Hide-4K: Underworld: Awakening has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,356 - plex-utills - Hide-4K: Resident Evil: Retribution has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,476 - plex-utills - Hide-4K: Alien: Covenant has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,600 - plex-utills - Hide-4K: The Hateful Eight has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,709 - plex-utills - Hide-4K: The Revenant has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,795 - plex-utills - Hide-4K: Taxi Driver has only 4k avaialble, setting untranscodable
2021-12-15 04:32:57,904 - plex-utills - Hide-4K: Resident Evil: Apocalypse has only 4k avaialble, setting untranscodable
2021-12-15 04:32:58,044 - plex-utills - Hide-4K: Resident Evil: The Final Chapter has only 4k avaialble, setting untranscodable
2021-12-15 04:32:58,148 - plex-utills - Hide-4K: Dune has only 4k avaialble, setting untranscodable
2021-12-15 04:32:58,247 - plex-utills - Hide-4K: Resident Evil: Extinction has only 4k avaialble, setting untranscodable
2021-12-15 04:32:58,247 - plex-utills - Hide-4K: Hide 4K Script has finished.
2022-01-08 20:33:43,095 - plex-utills - Hide-4K: Hide 4k films script starting now
2022-01-08 20:33:44,220 - plex-utills - Hide-4K: Up has only 4k avaialble, setting untranscodable
2022-01-08 20:33:44,414 - plex-utills - Hide-4K: Sympathy for Lady Vengeance has only 4k avaialble, setting untranscodable
2022-01-08 20:33:44,552 - plex-utills - Hide-4K: Sympathy for Mr. Vengeance has only 4k avaialble, setting untranscodable
2022-01-08 20:33:44,699 - plex-utills - Hide-4K: The Lord of the Rings: The Fellowship of the Ring has only 4k avaialble, setting untranscodable
2022-01-08 20:33:44,845 - plex-utills - Hide-4K: The Lord of the Rings: The Two Towers has only 4k avaialble, setting untranscodable
2022-01-08 20:33:44,943 - plex-utills - Hide-4K: Parasite has only 4k avaialble, setting untranscodable
2022-01-08 20:33:45,096 - plex-utills - Hide-4K: Star Wars: Episode IV - A New Hope has only 4k avaialble, setting untranscodable
2022-01-08 20:33:45,424 - plex-utills - Hide-4K: Finding Nemo has only 4k avaialble, setting untranscodable
2022-01-08 20:33:45,623 - plex-utills - Hide-4K: Monsters, Inc. has only 4k avaialble, setting untranscodable
2022-01-08 20:33:45,802 - plex-utills - Hide-4K: Batman Begins has only 4k avaialble, setting untranscodable
2022-01-08 20:33:45,959 - plex-utills - Hide-4K: Men in Black II has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,074 - plex-utills - Hide-4K: Terminator 2: Judgment Day has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,200 - plex-utills - Hide-4K: Star Wars: Episode V - The Empire Strikes Back has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,331 - plex-utills - Hide-4K: The Incredibles has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,459 - plex-utills - Hide-4K: Toy Story 3 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,552 - plex-utills - Hide-4K: WALL·E has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,708 - plex-utills - Hide-4K: The Hobbit: An Unexpected Journey has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,837 - plex-utills - Hide-4K: X-Men: The Last Stand has only 4k avaialble, setting untranscodable
2022-01-08 20:33:46,992 - plex-utills - Hide-4K: The Hobbit: The Battle of the Five Armies has only 4k avaialble, setting untranscodable
2022-01-08 20:33:47,116 - plex-utills - Hide-4K: Us has only 4k avaialble, setting untranscodable
2022-01-08 20:33:47,262 - plex-utills - Hide-4K: The Hobbit: The Desolation of Smaug has only 4k avaialble, setting untranscodable
2022-01-08 20:33:47,428 - plex-utills - Hide-4K: The Irishman has only 4k avaialble, setting untranscodable
2022-01-08 20:33:47,548 - plex-utills - Hide-4K: Once Upon a Time... In Hollywood has only 4k avaialble, setting untranscodable
2022-01-08 20:33:47,669 - plex-utills - Hide-4K: X-Men has only 4k avaialble, setting untranscodable
2022-01-08 20:33:47,822 - plex-utills - Hide-4K: X-Men: First Class has only 4k avaialble, setting untranscodable
2022-01-08 20:33:48,207 - plex-utills - Hide-4K: The Avengers has only 4k avaialble, setting untranscodable
2022-01-08 20:33:48,425 - plex-utills - Hide-4K: Django Unchained has only 4k avaialble, setting untranscodable
2022-01-08 20:33:48,572 - plex-utills - Hide-4K: Iron Man 3 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:48,683 - plex-utills - Hide-4K: Get Out has only 4k avaialble, setting untranscodable
2022-01-08 20:33:48,830 - plex-utills - Hide-4K: Thor: The Dark World has only 4k avaialble, setting untranscodable
2022-01-08 20:33:48,984 - plex-utills - Hide-4K: Avengers: Age of Ultron has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,106 - plex-utills - Hide-4K: X-Men: Days of Future Past has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,211 - plex-utills - Hide-4K: Dunkirk has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,340 - plex-utills - Hide-4K: Men in Black has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,483 - plex-utills - Hide-4K: Men in Black 3 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,636 - plex-utills - Hide-4K: Captain America: The Winter Soldier has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,768 - plex-utills - Hide-4K: Spider-Man: Into the Spider-Verse has only 4k avaialble, setting untranscodable
2022-01-08 20:33:49,938 - plex-utills - Hide-4K: Spider-Man: Homecoming has only 4k avaialble, setting untranscodable
2022-01-08 20:33:50,096 - plex-utills - Hide-4K: Battle Royale has only 4k avaialble, setting untranscodable
2022-01-08 20:33:50,220 - plex-utills - Hide-4K: Iron Man 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:50,369 - plex-utills - Hide-4K: Captain America: Civil War has only 4k avaialble, setting untranscodable
2022-01-08 20:33:50,529 - plex-utills - Hide-4K: Captain America: The First Avenger has only 4k avaialble, setting untranscodable
2022-01-08 20:33:51,025 - plex-utills - Hide-4K: Ant-Man has only 4k avaialble, setting untranscodable
2022-01-08 20:33:51,142 - plex-utills - Hide-4K: Thor has only 4k avaialble, setting untranscodable
2022-01-08 20:33:51,326 - plex-utills - Hide-4K: X-Men: Apocalypse has only 4k avaialble, setting untranscodable
2022-01-08 20:33:51,449 - plex-utills - Hide-4K: Deadpool has only 4k avaialble, setting untranscodable
2022-01-08 20:33:51,590 - plex-utills - Hide-4K: Deadpool 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:51,988 - plex-utills - Hide-4K: Black Widow has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,176 - plex-utills - Hide-4K: Star Wars: Episode IX - The Rise of Skywalker has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,321 - plex-utills - Hide-4K: Star Wars: Episode VII - The Force Awakens has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,459 - plex-utills - Hide-4K: Star Wars: Episode I - The Phantom Menace has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,587 - plex-utills - Hide-4K: Star Wars: Episode III - Revenge of the Sith has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,728 - plex-utills - Hide-4K: Star Wars: Episode VI - Return of the Jedi has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,846 - plex-utills - Hide-4K: Incredibles 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:52,941 - plex-utills - Hide-4K: Blade Runner has only 4k avaialble, setting untranscodable
2022-01-08 20:33:53,049 - plex-utills - Hide-4K: Blade has only 4k avaialble, setting untranscodable
2022-01-08 20:33:53,407 - plex-utills - Hide-4K: The Fifth Element has only 4k avaialble, setting untranscodable
2022-01-08 20:33:53,444 - plex-utills - 4k Posters: 4k HDR poster script starting now.
2022-01-08 20:33:53,567 - plex-utills - Hide-4K: Goodfellas has only 4k avaialble, setting untranscodable
2022-01-08 20:33:53,702 - plex-utills - Hide-4K: The Shawshank Redemption has only 4k avaialble, setting untranscodable
2022-01-08 20:33:53,828 - plex-utills - Hide-4K: Logan has only 4k avaialble, setting untranscodable
2022-01-08 20:33:53,935 - plex-utills - Hide-4K: Donnie Darko has only 4k avaialble, setting untranscodable
2022-01-08 20:33:54,063 - plex-utills - Hide-4K: Underworld has only 4k avaialble, setting untranscodable
2022-01-08 20:33:54,196 - plex-utills - Hide-4K: Alien has only 4k avaialble, setting untranscodable
2022-01-08 20:33:54,333 - plex-utills - Hide-4K: Schindler's List has only 4k avaialble, setting untranscodable
2022-01-08 20:33:54,460 - plex-utills - Hide-4K: Hellboy II: The Golden Army has only 4k avaialble, setting untranscodable
2022-01-08 20:33:54,556 - plex-utills - Hide-4K: The Mummy Returns has only 4k avaialble, setting untranscodable
2022-01-08 20:33:54,661 - plex-utills - Hide-4K: Underworld: Rise of the Lycans has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,008 - plex-utills - Hide-4K: The Martian has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,134 - plex-utills - Hide-4K: Saving Private Ryan has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,256 - plex-utills - Hide-4K: Inglourious Basterds has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,365 - plex-utills - Hide-4K: Underworld: Evolution has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,461 - plex-utills - Hide-4K: Full Metal Jacket has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,615 - plex-utills - Hide-4K: Resident Evil has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,710 - plex-utills - Hide-4K: Prometheus has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,828 - plex-utills - Hide-4K: Underworld: Awakening has only 4k avaialble, setting untranscodable
2022-01-08 20:33:55,928 - plex-utills - Hide-4K: Resident Evil: Retribution has only 4k avaialble, setting untranscodable
2022-01-08 20:33:56,058 - plex-utills - Hide-4K: Alien: Covenant has only 4k avaialble, setting untranscodable
2022-01-08 20:33:56,190 - plex-utills - Hide-4K: The Hateful Eight has only 4k avaialble, setting untranscodable
2022-01-08 20:33:56,309 - plex-utills - Hide-4K: The Revenant has only 4k avaialble, setting untranscodable
2022-01-08 20:33:56,610 - plex-utills - Hide-4K: Taxi Driver has only 4k avaialble, setting untranscodable
2022-01-08 20:33:56,751 - plex-utills - Hide-4K: Resident Evil: Apocalypse has only 4k avaialble, setting untranscodable
2022-01-08 20:33:56,890 - plex-utills - Hide-4K: Resident Evil: The Final Chapter has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,008 - plex-utills - Hide-4K: Dune has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,105 - plex-utills - Hide-4K: Resident Evil: Extinction has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,202 - plex-utills - Hide-4K: Soul has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,299 - plex-utills - Hide-4K: Cloverfield has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,389 - plex-utills - Hide-4K: Gladiator has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,487 - plex-utills - Hide-4K: Jumanji has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,588 - plex-utills - Hide-4K: E.T. the Extra-Terrestrial has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,698 - plex-utills - Hide-4K: Kick-Ass has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,802 - plex-utills - Hide-4K: Starship Troopers has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,881 - plex-utills - Hide-4K: Total Recall has only 4k avaialble, setting untranscodable
2022-01-08 20:33:57,969 - plex-utills - Hide-4K: Léon: The Professional has only 4k avaialble, setting untranscodable
2022-01-08 20:33:58,066 - plex-utills - Hide-4K: Edward Scissorhands has only 4k avaialble, setting untranscodable
2022-01-08 20:33:58,376 - plex-utills - Hide-4K: Casino has only 4k avaialble, setting untranscodable
2022-01-08 20:33:58,551 - plex-utills - Hide-4K: John Wick: Chapter 3 - Parabellum has only 4k avaialble, setting untranscodable
2022-01-08 20:33:58,670 - plex-utills - Hide-4K: Step Brothers has only 4k avaialble, setting untranscodable
2022-01-08 20:33:58,815 - plex-utills - Hide-4K: Venom: Let There Be Carnage has only 4k avaialble, setting untranscodable
2022-01-08 20:33:58,911 - plex-utills - Hide-4K: Don't Breathe 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,071 - plex-utills - Hide-4K: The Suicide Squad has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,198 - plex-utills - Hide-4K: Space Jam has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,350 - plex-utills - Hide-4K: Ant-Man and the Wasp has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,508 - plex-utills - Hide-4K: Avengers: Endgame has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,628 - plex-utills - Hide-4K: Avengers: Infinity War has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,783 - plex-utills - Hide-4K: Black Panther has only 4k avaialble, setting untranscodable
2022-01-08 20:33:59,941 - plex-utills - Hide-4K: Captain Marvel has only 4k avaialble, setting untranscodable
2022-01-08 20:34:00,051 - plex-utills - Hide-4K: 1917 has only 4k avaialble, setting untranscodable
2022-01-08 20:34:00,188 - plex-utills - Hide-4K: Doctor Strange has only 4k avaialble, setting untranscodable
2022-01-08 20:34:00,338 - plex-utills - Hide-4K: Guardians of the Galaxy has only 4k avaialble, setting untranscodable
2022-01-08 20:34:00,477 - plex-utills - Hide-4K: Guardians of the Galaxy Vol. 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:34:00,801 - plex-utills - Hide-4K: Interstellar has only 4k avaialble, setting untranscodable
2022-01-08 20:34:00,951 - plex-utills - Hide-4K: Iron Man has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,102 - plex-utills - Hide-4K: It has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,213 - plex-utills - Hide-4K: John Wick has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,351 - plex-utills - Hide-4K: John Wick: Chapter 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,435 - plex-utills - Hide-4K: Joker has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,577 - plex-utills - Hide-4K: The Lord of the Rings: The Return of the King has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,738 - plex-utills - Hide-4K: Rogue One: A Star Wars Story has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,859 - plex-utills - Hide-4K: Spider-Man has only 4k avaialble, setting untranscodable
2022-01-08 20:34:01,980 - plex-utills - Hide-4K: Spider-Man 2 has only 4k avaialble, setting untranscodable
2022-01-08 20:34:02,142 - plex-utills - Hide-4K: Spider-Man: Far from Home has only 4k avaialble, setting untranscodable
2022-01-08 20:34:02,297 - plex-utills - Hide-4K: Star Wars: Episode VIII - The Last Jedi has only 4k avaialble, setting untranscodable
2022-01-08 20:34:02,408 - plex-utills - Hide-4K: Thor: Ragnarok has only 4k avaialble, setting untranscodable
2022-01-08 20:34:02,486 - plex-utills - Hide-4K: Apocalypse Now has only 4k avaialble, setting untranscodable
2022-01-08 20:34:02,595 - plex-utills - Hide-4K: The Matrix has only 4k avaialble, setting untranscodable
2022-01-08 20:34:02,700 - plex-utills - Hide-4K: The Matrix Revolutions has only 4k avaialble, setting untranscodable
2022-01-08 20:34:03,053 - plex-utills - Hide-4K: The Matrix Reloaded has only 4k avaialble, setting untranscodable
2022-01-08 20:34:03,194 - plex-utills - Hide-4K: The Matrix Resurrections has only 4k avaialble, setting untranscodable
2022-01-08 20:34:03,327 - plex-utills - Hide-4K: Lights Out has only 4k avaialble, setting untranscodable
2022-01-08 20:34:03,414 - plex-utills - Hide-4K: Borat Subsequent Moviefilm has only 4k avaialble, setting untranscodable
2022-01-08 20:34:03,414 - plex-utills - Hide-4K: Hide 4K Script has finished.
2022-01-08 20:34:14,288 - plex-utills - Restore-posters: Restore backup posters starting now
2022-01-08 20:34:14,641 - plex-utills - 4k Posters: 4k HDR poster script starting now.
2022-01-08 21:13:02,687 - plex-utills - 4k Posters: 4k HDR poster script starting now.

**Comment by jkirkcaldy** [comment]
Can you post your docker logs after you have manually started the 4k poster script.

**Comment by AdamGoodApp** [comment]
INFO:4k Posters: 4k HDR poster script starting now.

Exception in thread Thread-2:

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.9/threading.py", line 910, in run

    self._target(*self._args, **self._kwargs)

  File "/app/app/scripts.py", line 544, in posters4k

    m = MediaInfo.parse(file, output='JSON')

  File "/usr/local/lib/python3.9/site-packages/pymediainfo/__init__.py", line 494, in parse

    raise FileNotFoundError(filename)

FileNotFoundError: /films/data/movies/8.DIAGRAM.POLE.FIGHTER.1984.720p.REPACK.XVID.SUBBED-MAJESTIC/8.DIAGRAM.POLE.FIGHTER.1984.720p.REPACK.XVID.SUBBED-MAJESTIC.avi


Seems to get stuck with finding this movie, I have deleted it from the system but still tries to find it?

**Comment by jkirkcaldy** [comment]
looks like the paths are wrong. 

it probably should be /films/movies rather than /films/data/

Can you send a screenshot of the /help window?

**Comment by AdamGoodApp** [comment]
<img width="1294" alt="Screen Shot 2022-01-11 at 0 31 10" src="https://user-images.githubusercontent.com/4471245/148792473-04397536-a9fd-4410-a1a1-2a89bd859181.png">

**Comment by jkirkcaldy** [comment]
and if you do `docker exec plex-utills /bin/bash -c "ls -l /films"` on your docker host (not inside the docker contaner) what's the result

**Comment by AdamGoodApp** [comment]
```
total 48
drwxr-xr-x   6 1000 1000  4096 Sep 28 01:49 anime
drwxr-xr-x  11 1000 1000  4096 Sep 18 21:16 comics
drwxr-xr-x   2 1000 1000 16384 Sep 13 15:04 lost+found
drwxr-xr-x 224 1000 1000 16384 Jan 11 00:20 movies
drwxr-xr-x   2 1000 1000  4096 Sep 13 15:12 music
drwxr-xr-x  19 1000 1000  4096 Jan 10 22:33 tv
```

**Comment by jkirkcaldy** [comment]
The dev update allows you to manually override teh plex path inside the plex-utills container. 

To try it, pull the :dev container and go to /admin_config

Scroll down until you see `Enable Plex File Path, Manual Override`
Change the settings so it looks like the below and click save at the bottom. It should then work. 

![image](https://user-images.githubusercontent.com/26098592/148998546-0f686cd8-d7cc-4077-86cb-fee1b9b58ac1.png)

**Comment by AdamGoodApp** [comment]
Thank you! Works fine now.
